### PR TITLE
Create mbmp_pt_BR.ts

### PR DESCRIPTION
**Pull request by marcelocripe**
Please accept the Brazilian Portuguese language translation for the MBMP program.

The file that has the latest translation can also be found at this URL: https://github.com/marcelocripe/MBMP_pt_BR/blob/main/mbmp_pt_BR.ts

Thank you for creating, maintaining and updating MBMP.

Thank you very much.

marcelocripe
(Original text in Brazilian Portuguese language)

- - - - -

Por favor, aceite a tradução do idioma o Português do Brasil para o programa MBMP.

O arquivo que possui a tradução mais recente também pode ser encontrado neste URL: https://github.com/marcelocripe/MBMP_pt_BR/blob/main/mbmp_pt_BR.ts

Eu agradeço por você criar, manter e atualizar o MBMP.

Muito obrigado.

marcelocripe
(Texto original em idioma Português do Brasil)

### CODE REVIEW

**Review by marcelocripe — COMMENTED** [review]
Second Committee on 11/24/2022

- - - - -

Segundo "Commit" do dia 24/11/2022

**Comment by andrew-bibb** [comment]
Marcelo,

Thank you for this.  I will need to update the build system for the translations so I want to do that before I merge the pull.  Won't be difficult, very similar to what I implemented in CMST.

Don't go out of your way to keep the translations current.  Even I don't really use this program anymore.  Very stupid of me but after working on it for a couple of years when I got ready to release it I discovered that because I link in GStreamer components I had to release under the GPL, and that is a problem for me.  I've never really done a formal release of it.  I mainly keep it up now in case somebody wants to see how to communicate with GStreamer over DBUS or how to implement an MPRIS interface, and of course it is available for anyone that wants to build it and use it.

**Comment by marcelocripe** [comment]
Hi Andrew.

"Thank you for this. I will need to update the build system for the translations so I want to do that before I merge the pull. Won't be difficult, very similar to what I implemented in CMST."
I hope that my translations from the pt-BR language were understandable for all Brazilians and that they were as good as the programs you develop.

"Don't go out of your way to keep the translations current. Even I don't really use this program anymore."
I hope one day to be able to learn how to create a .deb package from the source code and that way I will be able to see this program and the pt-BR translations in their proper places, then I will be able to assess whether the translation was coherent or not.

'Very stupid of me but after components working on it for a couple of years when I got ready to release it I discovered that because I link in GStreamer I had to release under the GPL, and that is a problem for me. I've never really done a formal release of it."
I still don't have full knowledge about the different types of licenses that are used in GNU/Linux and BSD.

"...and of course it is available to anyone that wants to build it and use it."
Until I learn how to do this, I'll just want to see the MBMP working.

Do you have any other program that I can help with the translation to pt-BR?

The other https://github.com/andrew-bibb/mbmp/pull/12 is for the MBMP .desktop file.

Thank you very much.

- - - - -

Olá Andrew.

"Thank you for this. I will need to update the build system for the translations so I want to do that before I merge the pull. Won't be difficult, very similar to what I implemented in CMST."
Eu espero que as minhas traduções do idioma pt-BR tenham ficado compreensíves para todos os Brasileiros e que tenham ficado tão boas quanto os programas que você desenvolve.

"Don't go out of your way to keep the translations current. Even I don't really use this program anymore."
Eu espero um dia poder aprender a criar pacote .deb a partir do código fonte e assim eu poderei ver este programa e as traduções pt-BR nos seus devidos lugares, aí sim eu poderei avaliar se a tradução ficou coerente ou não.

'Very stupid of me but after working on it for a couple of years when I got ready to release it I discovered that because I link in GStreamer components I had to release under the GPL, and that is a problem for me. I've never really done a formal release of it."
Eu ainda não possuo total conhecimento sobre os diversos tipos de licenças que são utilizadas no GNU/Linux e no BSD.

"...and of course it is available for anyone that wants to build it and use it."
Até que eu aprenda a fazer isso, eu ficarei apenas com a vontade de ver o MBMP funcionando.

Você tem mais algum outro programa que eu possa ajudar com a tradução para pt-BR?


O outro https://github.com/andrew-bibb/mbmp/pull/12 é referente ao arquivo .desktop do MBMP.

Muito obrigado.

**Comment by andrew-bibb** [comment]
Marcelo

I am going to bring your translations in, just need to revise the build system so that files are generated automatically like I do with CMST.  That was huge in reducing the effort required to package a release.  

As far as other programs I have a lot but not for public release.  In my day job I'm a structural engineer and I have written a bunch of programs that fill the niche between spreadsheets and full blown commercial frame analysis and design programs.  Releasing them would incur a lot of liability which my insurance won't cover so I need to keep them in-house. 

On the licensing front I ran afoul of the FSF many years ago by naively saying my code was GPL when it could not be because it linked with a non-free library.   You will never run across a more humorless bunch of people that won't take yes for an answer than the FSF.  Finally I just trashed the whole project and stopped writing any opensource programs for about 10 years.  I thought I'd be okay on MBMP and anyone can certainly release it under GPL by changing the license terms (perfectly acceptable), but I won't.

**Pull request merged**
